### ISSUE TITLE
Load variables in template-loading scope

### ISSUE THREAD

**Issue by GaryJones** [GaryJones/Gamajo-Template-Loader#13]
Calling in globals, and extracting variables from an array variable, then requiring the template file all in the same scope, so that the non-global variables don't pollute the global scope.

See https://github.com/blazersix/simple-image-widget/blob/develop/includes/class-simple-image-widget-template-loader.php#L194

cc @bradyvercher

**Comment by GaryJones** [comment]
@klihelp @bradyvercher What do you think of the referenced branch [changes](https://github.com/GaryJones/Gamajo-Template-Loader/commit/e78637ad0133d86ae51e363c44cf8dbc4ca501a3)?

Passing in custom template data is now as simple as:
~~~php
// Some plugin file
$data = array( 'foo' => 'bar', 'baz' => 'boom' );
$my_template_loader = new My_Template_Loader;
$my_template_loader->add_template_data( $data );
$my_template_loader->get_template_part( 'my-template' );

// my-template.php
<div><?php echo $template['foo']; ?></div>
~~~

That way, it still uses the native `load_template()` function, which already extracts variables from `$wp_query->query_var` and loads in the globals.



cc @pippinsplugins FYI.

**Comment by pippinsplugins** [comment]
:+1:

**Comment by joelataylor** [comment]
I'm all about this. Right now it's a matter of `global $var, $var2` in each template that's included. :+1:

**Comment by GaryJones** [comment]
I've been re-building Genesis eNews Widget (branch not pushed yet) with it, and the `$template` is working really well. By having to explicitly add values to the data array, it helps keep logic out of the template files.

**Comment by joelataylor** [comment]
Awesome, so when is `1.2.0` going to be released? :) Looks like you're pushing new commits.

**Comment by GaryJones** [comment]
Waiting to see if Brady and @klihelp have an opinion about the branch, and then likely merge and tag in the next few days.

**Comment by bradyvercher** [comment]
It looks like that should work. My only concerns are that it creates a dependency on a global variable, so there could be unintended side effects depending on how people manipulate `$wp_query`. As long as the template is included right after adding data, it probably won't cause any problems.

It could also lead to template data leaking into other templates if new data isn't added before each include, but that shouldn't necessarily cause any problems on its own, either. I'd say go for it if you're not worried about any of that.

**Comment by GaryJones** [comment]
> It could also lead to template data leaking into other templates if new data isn't added before each include

I purposefully decided to overwrite the `'template'` key each time, rather than merge new template data with old template data, so that leaking data shouldn't happen so often. Perhaps it would be better as a `set_template_data()` rather than `add_template_data()`? 

Also, no-one has to use any or all of the data in a particular template, but is a `clear_template_data()` or `unset_template_data()` warranted for completeness?

**Comment by klihelp** [comment]
Looks good, thank you @GaryJones
Really ```set_template_data()``` is descriptive rather than ```add_template_data()```, with the matching ```unset_template_data()```

What do you think of using ```$template_data``` rather than ```$template```?
- would match un/set_template_data function names
- would reply questions as What's in $template? (The data of course)
- page templates exists for pages post types, where the you have to set the Template Name. In this case the word template already have a meaning.

**Comment by GaryJones** [comment]
I'll change it to "set" and add the "unset" too.

> What do you think of using $template_data rather than $template?

I wanted to keep the variable name short.

One suggestion I've seen is to use `$this` as the variable, an object, and make the values property of it. Easy to change (in my branch):

~~~diff
public function set_template_data( array $data ) {
	global $wp_query;
-	$wp_query->query_vars['template'] = $data;
+	$wp_query->query_vars['this'] = (object) $data;
}
~~~

And then templates to use:

~~~php
// my-template.php
<div><?php echo $this->foo; ?></div>
~~~

That's shorter, more memorable due to familiarity, and more self-documenting.

**Comment by klihelp** [comment]
> Any other suggestions other than ```$template_data```
```$data```?

Objects looks good.

**Comment by joelataylor** [comment]
:+1: for `$data`

**Comment by GaryJones** [comment]
Latest push to branch: https://github.com/GaryJones/Gamajo-Template-Loader/commit/5ed843fdecbec86355816a30099f9f1994e0f908

**Comment by schlessera** [comment]
Don't know if this is still up for debate...

I personally find `$data` to be as self-explaining as `$variable`. How about `$context`, as that is what is missing for the template to do its job?

**Comment by GaryJones** [comment]
`$context` may be a better default, but how about the constructor taking a string param that names the template variable, or an optionally-used `set_template_variable_name()` that allows the default to be changed?

**Comment by GaryJones** [comment]
The `set_template_data()` method now accepts a second argument, which determines the name of the variable that the template data is under. Defaults to `data` still.

**Comment by cliffordp** [comment]
How can https://github.com/GaryJones/Gamajo-Template-Loader/tree/template-data be used _inside a shortcode_?

If my shortcode generates data and then pulls the appropriate template, `echo` in the template throws the rendered template to the top of the post (like putting `echo` in a regular shortcode). If I `return` in the template to then _add to_ the shortcode's output, it doesn't...

Example usage (within shortcode):
```
$output = '<div>';
$output .= myClass::load_template( 'hourly_full_vertical', $template_data ); // the template does PHP return, not echo
$output = '</div>';
```
Result:
`<div></div>`

Thanks for the help!

**Comment by GaryJones** [comment]
@cliffordp I don't completely follow, but [`ob_start()`](http://php.net/manual/en/function.ob-start.php) and [`ob_get_clean()`](http://php.net/manual/en/function.ob-get-clean.php) may help you.

```php
function my_shortcode_callback() {
    // Turn on output buffering.
    ob_start();

    // Include a template that tries to echo something
    include 'foobar.php'; // or load_template etc.

    // Return the buffered output, to make the shortcode callback happy.
    return ob_get_clean();
}
```

**Comment by cliffordp** [comment]
Worked like a charm. Thank so much. It was a long, hard day, ha ha. :+1:
