### ISSUE TITLE
Retrieving custom fields/post data when loading templates using the class.

### ISSUE THREAD

**Issue by BoweFrankema** [GaryJones/Gamajo-Template-Loader#18]
Hi Gary,

I've been spending most of today and yesterday trying to get this to work, but I'm afraid I'm a bit over my head here. What I'm trying to do is implement your class to load a template part from inside my plugin. The template part contains custom field queries and basic WordPress data (the_title etc). Sadly the custom field data seems to be unavailable when loading the template. It does fetch the Post Title and excerpt. 

I'm pretty sure it has something to do with how I use your class but I have no idea how to fix it.. 

My code that loads the template part
https://gist.github.com/BoweFrankema/c37844c56305aa2878c5

The template part:
https://gist.github.com/BoweFrankema/4b7ec2bbc8aee51bf27b

Any help would be awesome and thanks for creating the class :-)

**Comment by GaryJones** [comment]
Hi @BoweFrankema,

Couple of things I'd try:

1. Move the `$my_template_loader->get_template_part( 'testimonial-loop' );` down to inside the loop (line 30) - that way, `the_post()` has been called, and the globals (which presumably `get_field()` uses to work out which post ID it should be reading the meta from) are correctly set. That may mean it's finding and reading the same markup file over and over, but, hopefully, it will be parsing it out with different values when it does the `get_field()` calls.

2. My `get_template_part(...)` method only _returns_ the partial template file - so you'll need an `echo` against it at some point. You do have a `echo $template['testimonial-loop`] in your Gist, but `$template` doesn't seem to have been populated within the code you've shared.

**Comment by BoweFrankema** [comment]
Awesome, that did the trick. I got everything working now by simply moving the my_template_loader to the right place. Everything works as expected now. For those who might need find it useful here's the final code:

````
  <div id="wefoster-testimonials-content">

    <?php
    // Define custom query parameters
    $custom_query_args = array(
      'author' => bp_displayed_user_id(),
      'post_type' => 'testimonials',
      'posts_per_page' => 5,
      'paged' => $paged,
    );

    // Get current page and append to custom query parameters array
    $custom_query_args['paged'] = get_query_var('paged') ? get_query_var('paged') : 1;

    // Instantiate custom query
    $custom_query = new WP_Query($custom_query_args);

    // Pagination fix
    $temp_query = $wp_query;
    $wp_query = null;
    $wp_query = $custom_query;

    // Output custom query loop
    if ($custom_query->have_posts()) :
      while ($custom_query->have_posts()) :
        $custom_query->the_post();

        //Load our plugin template part
        $my_template_loader = new Cue_Template_Loader;
        $my_template_loader->get_template_part( 'testimonial-loop' );
        ?>

        <?php
          do_action('before_content');
          $my_template_loader;
          do_action('after_content');
        ?>

        <?php
      endwhile;
    endif;
    // Reset postdata
    wp_reset_postdata();

    // Custom query loop pagination
    ?>
    <?php if (function_exists('wp_pagenavi')) : ?>
      <?php wp_pagenavi(array('query' => $custom_query));
      ?>
    <?php else : ?>
      <div class="alignleft"><?php next_posts_link(__('&laquo; Older Entries'));
      ?></div>
      <div class="alignright"><?php previous_posts_link(__('Newer Entries &raquo;'));
      ?></div>
    <?php endif;
    ?>
    <?php
    // Reset main query object
    $wp_query = null;
    $wp_query = $temp_query;
    ?>

  </div>
````

Thanks for your help Gary!
