### ISSUE TITLE
YOUR_PLUGIN_DIR undefined constant in PHP 7

### ISSUE THREAD

**Issue by zackkatz** [GaryJones/Gamajo-Template-Loader#19]
> PHP Notice: Use of undefined constant `YOUR_PLUGIN_DIR` - assumed 'YOUR_PLUGIN_DIR'

Apparently in PHP 7, constants need to be defined, even if overridden by an extended class. Can this be updated safely to `'YOUR_PLUGIN_DIR'` (a string)?

https://github.com/GaryJones/Gamajo-Template-Loader/blob/develop/class-gamajo-template-loader.php#L52

**Comment by GaryJones** [comment]
That makes sense. I've even type-hinted it should be a string.

If you can do a PR against the `develop` branch, I'll happily merge.
