### ISSUE TITLE
 Theme children wordpress 4.7

### ISSUE THREAD

**Issue by Infolu** [GaryJones/Gamajo-Template-Loader#28]
Hello, I am implementing this class in my plugin but I noticed that it is not working for theme children, is there an incompatibility with wordpres 4.7 to work on theme children?

**Comment by GaryJones** [comment]
Can you be more specific please? What code have you currently tried?

You can see that we [add child themes](https://github.com/GaryJones/Gamajo-Template-Loader/blob/develop/class-gamajo-template-loader.php#L275-L278) to the top of the template paths stack (priority 1, with parent themes as priority 10) to check first.

**Comment by GaryJones** [comment]
Closing through lack of reporter feedback.
