### ISSUE TITLE
brightnucleus/shortcodes v0.2.9 requires gamajo/template-loader dev-template-data

### ISSUE THREAD

**Issue by alokstha1** [GaryJones/Gamajo-Template-Loader#43]
I'm not sure if this is the right place to raise an issue.

When I try to run `composer require gamajo/template-loader or composer require gaa/gaa-services`, I get this error.

`- brightnucleus/shortcodes v0.2.9 requires gamajo/template-loader dev-template-data -> no matching package found.
    - brightnucleus/shortcodes v0.2.8 requires gamajo/template-loader dev-template-data -> no matching package found.
    - brightnucleus/shortcodes v0.2.7 requires gamajo/template-loader dev-template-data -> no matching package found.
    - brightnucleus/shortcodes v0.2.6 requires gamajo/template-loader dev-template-data -> no matching package found.
    - brightnucleus/shortcodes v0.2.14 requires gamajo/template-loader dev-template-data -> no matching package found.
    - brightnucleus/shortcodes v0.2.13 requires gamajo/template-loader dev-template-data -> no matching package found.
    - brightnucleus/shortcodes v0.2.12 requires beberlei/assert dev-schlessera-138-functions-file-causes-collisions -> no matching package found.
    - brightnucleus/shortcodes v0.2.11 requires beberlei/assert dev-schlessera-138-functions-file-causes-collisions -> no matching package found.
    - brightnucleus/shortcodes v0.2.10 requires gamajo/template-loader dev-template-data -> no matching package found.
    - brightnucleus/config v0.2.5 requires beberlei/assert dev-schlessera-138-functions-file-causes-collisions -> no matching package found.
    - Conclusion: don't install gaa/corp-manager v2.1.7
    - Conclusion: don't install gaa/corp-manager v2.1.6
    - Conclusion: don't install gaa/corp-manager v2.1.5
    - Conclusion: don't install gaa/corp-manager v2.1.4
    - Conclusion: don't install gaa/corp-manager v2.1.3
    - Conclusion: don't install gaa/corp-manager v2.1.2
    - Conclusion: don't install gaa/corp-manager 2.1.1
    - Conclusion: remove brightnucleus/config v0.4.12
    - Conclusion: don't install brightnucleus/config v0.4.12
    - brightnucleus/shortcodes v0.2.0 requires brightnucleus/config 0.2.* -> satisfiable by brightnucleus/config[v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.4, v0.2.5, v0.2.6, v0.2.7, v0.2.8].
    - brightnucleus/shortcodes v0.2.1 requires brightnucleus/config ^0.2 -> satisfiable by brightnucleus/config[v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.4, v0.2.5, v0.2.6, v0.2.7, v0.2.8].
    - brightnucleus/shortcodes v0.2.2 requires brightnucleus/config ^0.2 -> satisfiable by brightnucleus/config[v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.4, v0.2.5, v0.2.6, v0.2.7, v0.2.8].
    - brightnucleus/shortcodes v0.2.3 requires brightnucleus/config ^0.2 -> satisfiable by brightnucleus/config[v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.4, v0.2.5, v0.2.6, v0.2.7, v0.2.8].
    - brightnucleus/shortcodes v0.2.4 requires brightnucleus/config ^0.2 -> satisfiable by brightnucleus/config[v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.4, v0.2.5, v0.2.6, v0.2.7, v0.2.8].
    - brightnucleus/shortcodes v0.2.5 requires brightnucleus/config ^0.2 -> satisfiable by brightnucleus/config[v0.2.0, v0.2.1, v0.2.2, v0.2.3, v0.2.4, v0.2.5, v0.2.6, v0.2.7, v0.2.8].
    - brightnucleus/shortcodes v0.2.15 requires brightnucleus/config ^0.2.4 -> satisfiable by brightnucleus/config[v0.2.4, v0.2.5, v0.2.6, v0.2.7, v0.2.8].
    - Can only install one of: brightnucleus/config[v0.2.0, v0.4.12].
    - Can only install one of: brightnucleus/config[v0.2.1, v0.4.12].
    - Can only install one of: brightnucleus/config[v0.2.2, v0.4.12].
    - Can only install one of: brightnucleus/config[v0.2.3, v0.4.12].
    - Can only install one of: brightnucleus/config[v0.2.4, v0.4.12].
    - Can only install one of: brightnucleus/config[v0.2.6, v0.4.12].
    - Can only install one of: brightnucleus/config[v0.2.7, v0.4.12].
    - Can only install one of: brightnucleus/config[v0.2.8, v0.4.12].`

What could be the possible issue?

Thank you in advance.

**Comment by GaryJones** [comment]
Hi @alokstha1,

If you go back far enough into the `brightnucleus/shortcode` repository ([to here](https://github.com/brightnucleus/shortcodes/blame/b09de48e66d9992851d98c4c4ba1ac2507145a88/composer.json#L22)), then you'll see that it once required the `dev-template-data` branch of this package.

However, [since 2016](https://github.com/brightnucleus/shortcodes/commit/3ef2941f18c6bec180f9eb59aba65dfaced4a8f6), it's used v1.2.0 of this package, which suggests that what you're working with needs to use an updated version of `brightnucleus/shortcode`.

Though I recognise the `composer require gaa/gaa-services` reference, I don't have access to see what version of `brightnucleus/shortcode` it used.

cc @schlessera.

**Comment by alokstha1** [comment]
Hi @GaryJones 

Thank you for your response.
`
packages: [
    "require": {
                "brightnucleus/config": ">=0.4.7",
                "brightnucleus/injector": ">=0.4.1",
                "brightnucleus/service-locator": ">=0.3",
                "composer/installers": "^1.0",
                "container-interop/container-interop": "^1.1",
                "doctrine/annotations": "^1.2",
                "goaop/framework": "^2",
                "pimple/pimple": "^3",
                "psr/log": "^1.0"
        }
]
`
This is in composer.json file. Please let me know if you have any questions.

Thank you.

**Comment by GaryJones** [comment]
You could try running `composer why brightnucleus/shortcodes` to see which of those packages pulls in the shortcodes one as a dependency.

**Comment by alokstha1** [comment]
Thank you for your response, @GaryJones.

I ran the command and got 
`gaa/gaa-futures-calculator  v3.4.1  requires  brightnucleus/shortcodes (^0.3)`
`gaa/gaa-member-area         v3.2.1  requires  brightnucleus/shortcodes (>=0.2.19)`  
`gaa/gaa-wasde               v4.3.1  requires  brightnucleus/shortcodes (^0.3.2)`

Not sure what to do with this. And `brightnucleus/shortcodes` looks different from one another plugins.
What should I do? Please help.

Thank you.

**Comment by GaryJones** [comment]
So it looks like the three `gaa/` packages you mentioned all need bumping the shortcodes dependency to `^0.4`.

At this point, it's now two levels away from this template loader package, and in the realm of the packages that GAA own.

**Comment by alokstha1** [comment]
Thank you @GaryJones for your response. Really appreciate it.

Just to confirm, so, are you suggesting that I should update the `brightnucleus/shortcodes` dependency version in those three `gaa/` packages to `^0.4`?

Thank you.

**Comment by GaryJones** [comment]
> Just to confirm, so, are you suggesting that I should update the brightnucleus/shortcodes dependency version in those three gaa/ packages to ^0.4?

Yes.

**Comment by alokstha1** [comment]
Cool.

Thanks alot @GaryJones.
